# ==============================================================================
# PROJECT METADATA
# ==============================================================================

name: ccopilot

description: >
  Chrome Copilot is a browser extension that helps you to navigate through the web.
  It provides you with a roadmap of the website you are currently visiting.
  It shows you the structure of the website, the number of pages, and the number of links.
  It also allows you to search for specific pages and links.
  You can also save your favorite pages and links for later use.

publish_to: "none"

version: 0.0.1

homepage: https://plugfox.dev

repository: https://github.com/plugfox/chrome_copilot

issue_tracker: https://github.com/plugfox/chrome_copilot/issues

#funding:
#  - https://www.buymeacoffee.com/
#  - https://www.patreon.com/
#  - https://boosty.to/

#topics:
#  -
#  -

#platforms:
#  android:
#  ios:
#  linux:
#  macos:
#  web:
#  windows:

#screenshots:
#  - description: 'Screenshot 1'
#    path: screenshot_1.png

# ==============================================================================
# PROJECT STRUCTURE
# ==============================================================================

# https://dart.dev/tools/pub/workspaces
#workspace:
#  - packages/ui
#  - packages/shared

#executables:
#  - tool/roadmap_schema.dart
#  - tool/roadmap_compile.dart
#  - tool/roadmap_fake.dart

# ==============================================================================
# DEPENDENCIES
# ==============================================================================

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  # Localization
  #intl: any

  # Annotation
  #json_annotation: ^4.9.0
  meta: any

  # Utility
  collection: any
  async: any
  convert: any
  #platform_info: ^5.0.0
  #multiline: ^3.0.0
  #rxdart: ^0.28.0
  #url_launcher: ^6.3.1
  #vector_math: ^2.1.4

  # Logger
  l: ^5.0.0

  # Transport and serialization
  #flat_buffers: ^23.5.26
  #protobuf: ^3.1.0

  # Web
  web: ^1.1.0

  # State management
  #control: ^0.2.0

  # Database
  #shared_preferences: ^2.3.5

  # Networking
  http: ^1.2.2
  #dio: ^5.4.2+1
  #dio_smart_retry: ^6.0.0

dev_dependencies:
  # Configuration
  #yaml: ^3.1.3
  #args: ^2.6.0

  # Linting
  lints: ^5.0.0

  # Testing
  test: any

  # Code generation
  build_runner: ^2.4.13
  build_web_compilers: ^4.1.3
  build: ^2.4.2
  pubspec_generator: ^4.1.0-pre.1
  #json_serializable: ^6.8.0
